import type { Task, Client } from "../types";

const CLIENT_COLORS = [
  "#3b82f6",
  "#22c55e",
  "#a855f7",
  "#ffaa00",
  "#06b6d4",
  "#ef4444",
  "#ec4899",
  "#14b8a6",
];

export const SEED_CLIENTS: Client[] = [
  {
    id: "c1",
    name: "Sunrise Cafe",
    company: "Sunrise Cafe LLC",
    email: "hello@sunrisecafe.com",
    defaultHourlyRate: 85,
    createdAt: "2025-01-15T10:00:00Z",
    color: CLIENT_COLORS[0],
  },
  {
    id: "c2",
    name: "Metro Printing Co",
    company: "Metro Print",
    email: "orders@metroprint.com",
    defaultHourlyRate: 65,
    createdAt: "2025-02-01T10:00:00Z",
    color: CLIENT_COLORS[1],
  },
  {
    id: "c3",
    name: "TechFlow Inc",
    company: "TechFlow",
    email: "design@techflow.io",
    defaultHourlyRate: 120,
    createdAt: "2025-01-20T10:00:00Z",
    color: CLIENT_COLORS[2],
  },
  {
    id: "c4",
    name: "Bella's Boutique",
    company: "Bella's",
    email: "bella@bellasboutique.com",
    defaultHourlyRate: 75,
    createdAt: "2025-03-01T10:00:00Z",
    color: CLIENT_COLORS[3],
  },
  {
    id: "c5",
    name: "Green Earth Landscaping",
    company: "Green Earth",
    email: "info@greenearth.com",
    defaultHourlyRate: 70,
    createdAt: "2025-02-15T10:00:00Z",
    color: CLIENT_COLORS[4],
  },
  {
    id: "c6",
    name: "Summit Real Estate",
    company: "Summit RE",
    email: "marketing@summitrealestate.com",
    defaultHourlyRate: 95,
    createdAt: "2025-01-10T10:00:00Z",
    color: CLIENT_COLORS[5],
  },
];

function daysAgo(n: number): string {
  return new Date(Date.now() - n * 86400000).toISOString();
}

export const SEED_TASKS: Task[] = [
  // === LEADS ===
  {
    id: "t1",
    title: "Cafe Website Redesign",
    clientId: "c1",
    projectType: "web_design",
    status: "lead",
    priority: "high",
    estimatedHours: 40,
    actualHours: 0,
    hourlyRate: 85,
    pnl: 0,
    revenue: 3400,
    progress: 0,
    createdAt: daysAgo(2),
    dueDate: daysAgo(-14),
    order: 0,
    description: "Full responsive redesign with online ordering integration",
  },
  {
    id: "t2",
    title: "Business Card Set",
    clientId: "c4",
    projectType: "printing",
    status: "lead",
    priority: "medium",
    estimatedHours: 3,
    actualHours: 0,
    hourlyRate: 75,
    pnl: 0,
    revenue: 225,
    progress: 0,
    createdAt: daysAgo(1),
    dueDate: daysAgo(-7),
    order: 1,
  },

  // === IN PROGRESS ===
  {
    id: "t3",
    title: "Flyer Printing Package",
    clientId: "c2",
    projectType: "printing",
    status: "in_progress",
    priority: "medium",
    estimatedHours: 8,
    actualHours: 3,
    hourlyRate: 65,
    pnl: 0,
    revenue: 520,
    progress: 60,
    createdAt: daysAgo(5),
    startedAt: daysAgo(3),
    dueDate: daysAgo(-2),
    order: 0,
  },
  {
    id: "t4",
    title: "E-Commerce Site",
    clientId: "c3",
    projectType: "web_design",
    status: "in_progress",
    priority: "urgent",
    estimatedHours: 60,
    actualHours: 25,
    hourlyRate: 120,
    pnl: 0,
    revenue: 7200,
    progress: 42,
    createdAt: daysAgo(14),
    startedAt: daysAgo(10),
    dueDate: daysAgo(-5),
    order: 1,
  },
  {
    id: "t5",
    title: "Brand Identity Package",
    clientId: "c5",
    projectType: "branding",
    status: "in_progress",
    priority: "high",
    estimatedHours: 20,
    actualHours: 8,
    hourlyRate: 70,
    pnl: 0,
    revenue: 1400,
    progress: 40,
    createdAt: daysAgo(7),
    startedAt: daysAgo(5),
    order: 2,
  },

  // === WAITING ON CLIENT ===
  {
    id: "t6",
    title: "Branding Package",
    clientId: "c4",
    projectType: "branding",
    status: "waiting",
    priority: "medium",
    estimatedHours: 15,
    actualHours: 10,
    hourlyRate: 75,
    pnl: 0,
    revenue: 1125,
    progress: 80,
    createdAt: daysAgo(10),
    startedAt: daysAgo(8),
    order: 0,
    description: "Awaiting client feedback on logo concepts",
  },

  // === COMPLETED (recent, for dashboard) ===
  {
    id: "t7",
    title: "Landing Page",
    clientId: "c3",
    projectType: "web_design",
    status: "completed",
    priority: "high",
    estimatedHours: 12,
    actualHours: 9,
    hourlyRate: 120,
    pnl: 360,
    revenue: 1440,
    progress: 100,
    createdAt: daysAgo(15),
    startedAt: daysAgo(12),
    completedAt: daysAgo(0),
    order: 0,
  },
  {
    id: "t8",
    title: "Menu Printing",
    clientId: "c1",
    projectType: "printing",
    status: "completed",
    priority: "low",
    estimatedHours: 4,
    actualHours: 3,
    hourlyRate: 85,
    pnl: 85,
    revenue: 340,
    progress: 100,
    createdAt: daysAgo(8),
    startedAt: daysAgo(6),
    completedAt: daysAgo(0),
    order: 1,
  },
  {
    id: "t9",
    title: "Social Media Kit",
    clientId: "c4",
    projectType: "branding",
    status: "completed",
    priority: "medium",
    estimatedHours: 6,
    actualHours: 7,
    hourlyRate: 75,
    pnl: -75,
    revenue: 450,
    progress: 100,
    createdAt: daysAgo(12),
    startedAt: daysAgo(10),
    completedAt: daysAgo(1),
    order: 2,
  },
  {
    id: "t10",
    title: "Property Brochure",
    clientId: "c6",
    projectType: "printing",
    status: "completed",
    priority: "high",
    estimatedHours: 10,
    actualHours: 8,
    hourlyRate: 95,
    pnl: 190,
    revenue: 950,
    progress: 100,
    createdAt: daysAgo(20),
    startedAt: daysAgo(18),
    completedAt: daysAgo(3),
    order: 3,
  },
  {
    id: "t11",
    title: "Corporate Website",
    clientId: "c6",
    projectType: "web_design",
    status: "completed",
    priority: "urgent",
    estimatedHours: 50,
    actualHours: 45,
    hourlyRate: 95,
    pnl: 475,
    revenue: 4750,
    progress: 100,
    createdAt: daysAgo(45),
    startedAt: daysAgo(40),
    completedAt: daysAgo(5),
    order: 4,
  },
  {
    id: "t12",
    title: "Logo Design",
    clientId: "c5",
    projectType: "branding",
    status: "completed",
    priority: "medium",
    estimatedHours: 8,
    actualHours: 6,
    hourlyRate: 70,
    pnl: 140,
    revenue: 560,
    progress: 100,
    createdAt: daysAgo(25),
    startedAt: daysAgo(22),
    completedAt: daysAgo(7),
    order: 5,
  },
  {
    id: "t13",
    title: "Newsletter Template",
    clientId: "c3",
    projectType: "web_design",
    status: "completed",
    priority: "low",
    estimatedHours: 5,
    actualHours: 4,
    hourlyRate: 120,
    pnl: 120,
    revenue: 600,
    progress: 100,
    createdAt: daysAgo(30),
    startedAt: daysAgo(28),
    completedAt: daysAgo(10),
    order: 6,
  },

  // === LOST ===
  {
    id: "t14",
    title: "Postcard Order",
    clientId: "c6",
    projectType: "printing",
    status: "lost",
    priority: "low",
    estimatedHours: 5,
    actualHours: 0,
    hourlyRate: 95,
    pnl: -475,
    revenue: 475,
    progress: 0,
    createdAt: daysAgo(20),
    completedAt: daysAgo(15),
    order: 0,
    description: "Client went with competitor",
  },
  {
    id: "t15",
    title: "App UI Mockup",
    clientId: "c3",
    projectType: "web_design",
    status: "lost",
    priority: "high",
    estimatedHours: 25,
    actualHours: 5,
    hourlyRate: 120,
    pnl: -600,
    revenue: 3000,
    progress: 0,
    createdAt: daysAgo(35),
    completedAt: daysAgo(25),
    order: 1,
    description: "Project cancelled by client",
  },
];
